/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.pi.visao;

import br.senac.pi.dao.ConectaDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaCadastroProduto extends javax.swing.JInternalFrame {
    Connection Conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private Object cbEmpresaProduto;
    private Object usuario;
    

    

    /**
     * Creates new form TelaCadastroProduto
     */
     public  TelaCadastroProduto() throws ClassNotFoundException, SQLException {
        initComponents();
        this.Conn = ConectaDB.conectaDB();
         preencheCBMarcaProduto();
         preencheCBEmpresaProduto();
    } 
    private void preencheCBMarcaProduto() throws SQLException {
        List<String> listaMarcas = new ArrayList<String>();
        String sql = "SELECT * FROM marca;";
        pst = this.Conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while (rs.next()){
            listaMarcas.add(rs.getString("descricao"));
     
        }
        // Instalando o DefultComboModel
        DefaultComboBoxModel defaultComboBox = new DefaultComboBoxModel(listaMarcas.toArray());
        // passando os valores do "model" pro ComboBox
        cbMarcaProduto.setModel(defaultComboBox);
        pst.close();
    }
     private void preencheCBEmpresaProduto() throws SQLException{
        List<String> listaEmpresas = new ArrayList<String>();
         String sql = "SELECT id, razao_social FROM empresa;";
            pst = this.Conn.prepareStatement(sql);
           rs = pst.executeQuery();
     
           while (rs.next()){
              listaEmpresas.add(rs.getString("razao_social"));
         
          }
         DefaultComboBoxModel defaultComboBox = new DefaultComboBoxModel(listaEmpresas.toArray());
          cbEmpresaCadastroProduto.setModel(defaultComboBox);
          
          this.Conn.close();
                   
           
           
                   
         
     }
             
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmailEmpresa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNomeProdutoProduto = new javax.swing.JTextField();
        txtCodigoBarrasProduto = new javax.swing.JTextField();
        txtIdTipoProdutoProduto = new javax.swing.JTextField();
        txtUnidadeMedidaProduto = new javax.swing.JTextField();
        txtStatusProdutoProduto = new javax.swing.JTextField();
        txtDataCadastroProduto = new javax.swing.JTextField();
        bntCadastrarProduto = new javax.swing.JButton();
        bntLimparCampos = new javax.swing.JButton();
        cbMarcaProduto = new javax.swing.JComboBox<>();
        cbEmpresaCadastroProduto = new javax.swing.JComboBox<>();

        txtEmailEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailEmpresaActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(153, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Cadastro de Produto");

        jLabel2.setText("Nome do Produto");

        jLabel3.setText("Codigo de Barras");

        jLabel4.setText("Data de Cadastro");

        jLabel5.setText("Empresa");

        jLabel6.setText(" Marca");

        jLabel7.setText("ID do Tipo de Produdo");

        jLabel8.setText("ID Unidade de Medida");

        jLabel9.setText("ID do Status do Produto");

        txtNomeProdutoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoProdutoActionPerformed(evt);
            }
        });

        txtCodigoBarrasProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarrasProdutoActionPerformed(evt);
            }
        });

        txtIdTipoProdutoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTipoProdutoProdutoActionPerformed(evt);
            }
        });

        txtUnidadeMedidaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadeMedidaProdutoActionPerformed(evt);
            }
        });

        txtStatusProdutoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusProdutoProdutoActionPerformed(evt);
            }
        });

        txtDataCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataCadastroProdutoActionPerformed(evt);
            }
        });

        bntCadastrarProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bntCadastrarProduto.setText("Cadastrar Produto");
        bntCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarProdutoActionPerformed(evt);
            }
        });

        bntLimparCampos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntLimparCampos.setText("Limpar");
        bntLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLimparCamposActionPerformed(evt);
            }
        });

        cbMarcaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbEmpresaCadastroProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(bntCadastrarProduto)
                        .addGap(55, 55, 55)
                        .addComponent(bntLimparCampos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(279, 279, 279))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCodigoBarrasProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeProdutoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEmpresaCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUnidadeMedidaProduto)
                        .addComponent(txtIdTipoProdutoProduto)
                        .addComponent(cbMarcaProduto, 0, 342, Short.MAX_VALUE)
                        .addComponent(txtStatusProdutoProduto))
                    .addComponent(jLabel9))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 378, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeProdutoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoBarrasProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdTipoProdutoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtUnidadeMedidaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtStatusProdutoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEmpresaCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntCadastrarProduto)
                            .addComponent(bntLimparCampos)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEmpresaActionPerformed

    private void txtNomeProdutoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoProdutoActionPerformed

    private void txtCodigoBarrasProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarrasProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarrasProdutoActionPerformed

    private void txtIdTipoProdutoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTipoProdutoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTipoProdutoProdutoActionPerformed

    private void txtUnidadeMedidaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadeMedidaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadeMedidaProdutoActionPerformed

    private void txtStatusProdutoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusProdutoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusProdutoProdutoActionPerformed

    private void txtDataCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCadastroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataCadastroProdutoActionPerformed

    private void bntCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO produtos (descricao, codigo_barras) VALEUS (?, ?);";  
      
        String nomeProduto = "";
        int codigoBarras = 0;
        nomeProduto = txtNomeProdutoProduto.getText();
        codigoBarras = Integer.parseInt(txtCodigoBarrasProduto.getText());
        JOptionPane.showMessageDialog(this, "Nome Produto:" + nomeProduto + "\n" + "codigoBarras:" + codigoBarras); 
        }
              
    {          
    }//GEN-LAST:event_bntCadastrarProdutoActionPerformed

    private void bntLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimparCamposActionPerformed
        // TODO add your handling code here:
        txtNomeProdutoProduto.setText("");
        txtCodigoBarrasProduto.setText("");
        txtNomeProdutoProduto.requestFocus();
    }//GEN-LAST:event_bntLimparCamposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrarProduto;
    private javax.swing.JButton bntLimparCampos;
    private javax.swing.JComboBox<String> cbEmpresaCadastroProduto;
    private javax.swing.JComboBox<String> cbMarcaProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCodigoBarrasProduto;
    private javax.swing.JTextField txtDataCadastroProduto;
    private javax.swing.JTextField txtEmailEmpresa;
    private javax.swing.JTextField txtIdTipoProdutoProduto;
    private javax.swing.JTextField txtNomeProdutoProduto;
    private javax.swing.JTextField txtStatusProdutoProduto;
    private javax.swing.JTextField txtUnidadeMedidaProduto;
    // End of variables declaration//GEN-END:variables

   
 

   
   
     
    

}

  
    

